### ISSUE TITLE
User that includes GID should be valid.

### ISSUE THREAD

**Issue by rany2** [k9withabone/compose_spec_rs#23]
Please check the following related issue from a project that depends on this library: https://github.com/containers/podlet/issues/106

In short, this compose file is invalid according to the library:

```
version: "3.7"
services:
  true:
    image: 'docker.io/busybox'
    command: 'true'
    user: 999:999
```

When the `:999` GID portion is dropped, it works fine. It appears that the current implementation doesn't split `:` to get the group portion.
