### ISSUE TITLE
[windows] Parsing  anonymous Service#volumes raise AbsoluteContainerPath

### ISSUE THREAD

**Issue by axel7083** [k9withabone/compose_spec_rs#38]
I was not able to find the specification, but here is the example from the official repository [docker/awesome-compose#angular](https://github.com/docker/awesome-compose/blob/master/angular/compose.yaml)

The compose is the following

```yaml
services:
  web:
    build:
      context: angular
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules # <-- problematic line
```

I was looking at the [containers/podman-compose](https://github.com/containers/podman-compose) project, and this case is commented as followed 

> Anonymous: Just specify a path and let the engine creates the volume[^1]

It seems that they consider the following, if the short mount is only a path, it must be volume that is anonymous (not explicitly defined)

[^1]: https://github.com/containers/podman-compose/blob/d79ff01e7711959b277197bc0a9c7b5790d1d0a0/podman_compose.py#L139-L142
